### ISSUE TITLE
HTTP 400

### ISSUE THREAD

**Issue by lretq** [DiscordHooks/gitlab-ci-discord-webhook#8]
Hello, whenever the job is run, it fails with a http 400. Testing from local curl works (without the env variables), could it be that any unsupported characters are used?

**Comment by iamtraction** [comment]
Yeah, it is most like that.

You could fork the repo and update the `send.sh` file and add the verbose flag (`-v`) to the `curl` command and then when you use your fork's url instead of this repo's url in gitlab config you can see the request body in the logs. Using that you can see what's the unsupported character or if some character is not being escaped properly.

**Comment by lretq** [comment]
Yup, will try
